spring:
  application:
    name: auth-service
  config:
    import: "configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:9999}"

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health, info