version: '3.8'

services:
  postgresql:
    image: postgis/postgis:15-3.3
    container_name: openspot-postgresql
    environment:
      POSTGRES_DB: openspot
      POSTGRES_USER: openspot
      POSTGRES_PASSWORD: openspot
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./scripts/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    networks:
      - openspot-network

  redis:
    image: redis:7.2-alpine
    container_name: openspot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - openspot-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: openspot-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - openspot-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: openspot-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - openspot-network

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  kafka_data:
    driver: local

networks:
  openspot-network:
    driver: bridge