spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:openspot}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
      default_schema: auth
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: auth
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    default-schema: auth
    
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DB:0}
    password: ${REDIS_PASSWORD:}
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope: 
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://www.googleapis.com/oauth2/v3/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
            
jwt:
  secret: ${JWT_SECRET:openspot-jwt-secret-key-for-development-only}
  expiration: 86400000 # 24 hours

app:
  frontend:
    base-url: ${FRONTEND_BASE_URL:http://localhost:3000}
    auth-success-path: ${FRONTEND_AUTH_SUCCESS_PATH:/auth/login/success}
    auth-error-path: ${FRONTEND_AUTH_ERROR_PATH:/auth/login/error}

server:
  port: 8081
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh

resilience4j:
  circuitbreaker:
    instances:
      google-oauth:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10