spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/openspot
    username: openspot
    password: openspot
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope: profile, email
            
jwt:
  secret: ${JWT_SECRET:openspot-jwt-secret-key-for-development-only}
  expiration: 86400000 # 24 hours

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health, info

resilience4j:
  circuitbreaker:
    instances:
      google-oauth:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10