# ==============================================================================
# Promtail Configuration for Log Shipping
# ==============================================================================

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # ===========================================================================
  # Application logs from services
  # ===========================================================================
  - job_name: application-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: open-spot-services
          __path__: /app/logs/*.log

    pipeline_stages:
      # Parse log level
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3})\s+(?P<level>\w+)\s+(?P<thread>\[.*?\])\s+(?P<logger>[\w\.]+)\s+:\s+(?P<message>.*)'

      # Extract labels
      - labels:
          level:
          logger:

      # Timestamp parsing
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05.000'

  # ===========================================================================
  # System logs (optional)
  # ===========================================================================
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log
