apiVersion: v1
kind: ConfigMap
metadata:
  name: openspot-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "openspot.labels" . | nindent 4 }}
data:
  # Database configuration
  POSTGRES_HOST: {{ .Values.config.postgresHost | quote }}
  POSTGRES_PORT: {{ .Values.config.postgresPort | quote }}
  POSTGRES_DB: {{ .Values.config.postgresDb | quote }}
  POSTGRES_USER: {{ .Values.config.postgresUser | quote }}

  # Redis configuration
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}

  # Kafka configuration
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafkaBootstrapServers | quote }}
  ZOOKEEPER_CONNECT: {{ .Values.config.zookeeperConnect | quote }}

  # Spring Cloud Config
  SPRING_CLOUD_CONFIG_URI: {{ .Values.config.springCloudConfigUri | quote }}

  # Service discovery configuration for Gateway routing
  AUTH_SERVICE_HOST: {{ .Values.config.authServiceHost | quote }}
  AUTH_SERVICE_PORT: {{ .Values.config.authServicePort | quote }}
  LOCATION_SERVICE_HOST: {{ .Values.config.locationServiceHost | quote }}
  LOCATION_SERVICE_PORT: {{ .Values.config.locationServicePort | quote }}
  NOTIFICATION_SERVICE_HOST: {{ .Values.config.notificationServiceHost | quote }}
  NOTIFICATION_SERVICE_PORT: {{ .Values.config.notificationServicePort | quote }}

  # Frontend configuration
  FRONTEND_BASE_URL: {{ .Values.config.frontendBaseUrl | quote }}
  FRONTEND_AUTH_SUCCESS_PATH: {{ .Values.config.frontendAuthSuccessPath | quote }}
  FRONTEND_AUTH_ERROR_PATH: {{ .Values.config.frontendAuthErrorPath | quote }}

  # OAuth2 Google Redirect URI (must match Google OAuth Console settings)
  # Gateway를 통한 외부 URL 사용 (클라이언트에서 접근 가능한 주소)
  OAUTH2_REDIRECT_URI: {{ .Values.config.oauth2RedirectUri | quote }}
