apiVersion: v1
kind: ConfigMap
metadata:
  name: openspot-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "openspot.labels" . | nindent 4 }}
data:
  # Database configuration
  POSTGRES_HOST: "postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: {{ .Values.postgresql.env.POSTGRES_DB | quote }}
  POSTGRES_USER: {{ .Values.postgresql.env.POSTGRES_USER | quote }}

  # Redis configuration
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  # Kafka configuration
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  ZOOKEEPER_CONNECT: "zookeeper:2181"

  # Spring Cloud Config
  SPRING_CLOUD_CONFIG_URI: "http://config-service:9999"

  # Service discovery configuration for Gateway routing
  AUTH_SERVICE_HOST: "auth-service"
  AUTH_SERVICE_PORT: "8081"
  LOCATION_SERVICE_HOST: "location-service"
  LOCATION_SERVICE_PORT: "8082"
  NOTIFICATION_SERVICE_HOST: "notification-service"
  NOTIFICATION_SERVICE_PORT: "8083"

  # Frontend configuration
  FRONTEND_BASE_URL: "http://openspot.local"
  FRONTEND_AUTH_SUCCESS_PATH: "/login"
  FRONTEND_AUTH_ERROR_PATH: "/login/error"
